CUDA_VISIBLE_DEVICES=0 python main.py \
    --type train \
    --batch_size 6 \
    --imsize 512 \
    --cropsize 512 \
    --lr 1e-4 \
    --max_iter 100001 \
    --model_type baseline \
    --DA_comment Indicator_Test \
    --ST_comment Decoder_Test \
    --check_iter 250 \
    --is_da_train True \
    --is_st_train False \